nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # Tu peux mettre ici l'URL de ton frontend pour plus de sécurité
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/': ~    